spring.application.name=bankapp-backend
server.port=8080

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/bankapp_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=BankAppSecretKey2025SumiranPaparkarFullStackProject
app.jwt.expiration=86400000

# Account number prefix
app.account.prefix=BANK